name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO111MODULE: "on"

jobs:

  lint:
      runs-on: ubuntu-latest
      steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Linters
        uses: golangci/golangci-lint-action@v2

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Build
      run: mkdir .build && go build -o .build/ ./cmd/...

    - name: Test
      run: go test -v -count=100 -race -gcflags=-l -timeout=30s ./...
